app:
  build: .
  command: 'foreman s -p 3000'
  volumes:
    - .:/app
  ports:
    - "3000"
  links:
    - mysql
    - redis
    - elasticsearch
mysql:
  image: mysql:5.7.25
  ports:
    - "3306"
  environment:
    - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
redis:
  image: redis:3.2.3
  ports:
    - "6379"
elasticsearch:
  image: elasticsearch:6.6.2
  ports:
    - "9200"
